export const CHORD_TONIC = 'CHORD_TONIC';
export const CHORD_TYPE = 'CHORD_TYPE';
export const CHORD_NOTES = 'CHORD_NOTES';
export const FRETBOARD_NUMSTRINGS = 'FRETBOARD_NUMSTRINGS';
export const FRETBOARD_FRETSPAN = 'FRETBOARD_FRETSPAN';
export const FRETBOARD_POSITION = 'FRETBOARD_POSITION';
export const FRETBOARD_NOTES = 'FRETBOARD_NOTES';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
